{
 "title": "Cryptocurrency OHLC Live Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "coin_dash",
    "label": "Select Cryptocurrency",
    "query": {
     "query": "label_values(close_price_1m_stats, symbol)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Open Price for ${coin_dash} ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "open_price_1m_stats{symbol=\"$coin_dash\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Close Price for ${coin_dash} ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "close_price_1m_stats{symbol=\"$coin_dash\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest Price in 1h for ${coin_dash}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(high_price_1m_stats{symbol=\"$coin_dash\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lowest Price in 1h for ${coin_dash}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(low_price_1m_stats{symbol=\"$coin_dash\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volatility for ${coin_dash} Coin",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  stddev_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[1h]) \r\n  / \r\n  avg_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[1h])\r\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "1h Price Change %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(  close_price_1m_stats{symbol=\"$coin_dash\"} - close_price_1m_stats{symbol=\"$coin_dash\"} offset 30m\r\n)\r\n/ close_price_1m_stats{symbol=\"$coin_dash\"} offset 30m * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Price Action", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Candlestick",
   "type": "candlestick",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "last_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[1h])",
     "legendFormat": "A"
    },
    {
     "expr": "last_over_time(high_price_1m_stats{symbol=\"$coin_dash\"}[1h])",
     "legendFormat": "B"
    },
    {
     "expr": "last_over_time(low_price_1m_stats{symbol=\"$coin_dash\"}[1h])",
     "legendFormat": "C"
    },
    {
     "expr": "last_over_time(open_price_1m_stats{symbol=\"$coin_dash\"}[1h])",
     "legendFormat": "D"
    }
   ]
  },
  {
   "title": "Close Price of ${coin_dash} Coin",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "close_price_1m_stats{symbol=\"$coin_dash\"}",
     "legendFormat": "close_price"
    },
    {
     "expr": "sum_over_time( (close_price_1m_stats{symbol=\"$coin_dash\"} * volume_price_1m_stats{symbol=\"$coin_dash\"})[1h:]) \r\n/ \r\nsum_over_time(volume_price_1m_stats{symbol=\"$coin_dash\"}[1h:])",
     "legendFormat": "VWAP"
    },
    {
     "expr": "avg_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[50m])",
     "legendFormat": "SMA 50m"
    },
    {
     "expr": "avg_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[200m])",
     "legendFormat": "SMA 200m"
    }
   ]
  },
  {
   "title": "Bollinger Bands",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "avg_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[30m])",
     "legendFormat": "SMA"
    },
    {
     "expr": "avg_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[30m]) + (2 * stddev_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[30m]))",
     "legendFormat": "upper_band"
    },
    {
     "expr": "avg_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[30m]) - (2 * stddev_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[30m]))",
     "legendFormat": "lower_band"
    }
   ]
  },
  { "title": "Volume & Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Base Volume for ${coin_dash} Coin",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "volume_price_1m_stats{symbol=\"$coin_dash\"}",
     "legendFormat": "base_volume 1m"
    },
    {
     "expr": "avg_over_time(volume_price_1m_stats{symbol=\"$coin_dash\"}[20m])",
     "legendFormat": "Vol SMA 20"
    }
   ]
  },
  {
   "title": "DSI Approximation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "close_price_1m_stats{symbol=\"$coin_dash\"} - close_price_1m_stats{symbol=\"$coin_dash\"} offset 10m",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative Strength Index (RSI)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "100 - (100 / (1 + (avg_over_time(clamp_min(idelta(close_price_1m_stats{symbol=\"$coin_dash\"}[1m]), 0)[14m:]) / abs(avg_over_time(clamp_max(idelta(close_price_1m_stats{symbol=\"$coin_dash\"}[1m]), 0)[14m:])))))",
     "legendFormat": "RSI 14m"
    }
   ]
  },
  {
   "title": "MACD",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "avg_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[12m]) - avg_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[26m])",
     "legendFormat": "MACD Line"
    },
    {
     "expr": "avg_over_time((avg_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[12m]) - avg_over_time(close_price_1m_stats{symbol=\"$coin_dash\"}[26m]))[9m:])",
     "legendFormat": "Signal Line"
    }
   ]
  },
  { "title": "Market Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Market Overview (All Coins)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    { "expr": "close_price_1m_stats", "legendFormat": "Price" },
    {
     "expr": "(close_price_1m_stats - close_price_1m_stats offset 1h) / close_price_1m_stats offset 1h * 100",
     "legendFormat": "1h Change %"
    },
    {
     "expr": "sum_over_time(volume_price_1m_stats[24h])",
     "legendFormat": "24h Volume"
    }
   ]
  }
 ]
}